// SPDX-License-Identifier: MIT
#ifndef STUMBLEFISH_COMPANION_VERSIONS_H
#define STUMBLEFISH_COMPANION_VERSIONS_H

#ifdef TRACK_MY_PHONE
#ifndef TRACKFISH_VERSION
#define TRACKFISH_VERSION "1.0"
#endif
#endif // TRACK_MY_PHONE
#endif // STUMBLEFISH_COMPANION_VERSIONS_H
