;; SPDX-License-Identifier: MIT
;;
;; in the General section, the keys 'available', 'supported', and 'default'
;; refer to the names of the [group] following later in the file.
;;
;; each [group] has the following keys:
;;
;; id            - a unique (in this file) numerical ID
;; name          - the display name of the service
;; method        - HTTP Method to use for submission GET or POST (or PUT???)
;; urlTemplate   - an example URL to be shown in the UI
;; urlPath       - a path segment to be appended to the user-specified URL
;;                 the query (?foo=) will usually be appended to this.
;; hasSession    - whether a "Session ID" appears in URL or payload
;; hasDevice     - whether a "Device ID" or "Device Name" appears in the URL or payload

[General]
available=ncpt, traccar, custom
supported=ncpt, traccar, custom
default=ncpt

;; Nextcloud PhoneTrack:
;; GET to: https://your.server.org/NC_PATH_IF_NECESSARY/index.php/apps/phonetrack/logGet/TOKEN/DEVNAME
;; POST to: https://your.server.org/NC_PATH_IF_NECESSARY/index.php/apps/phonetrack/logPost/TOKEN/DEVNAME
;; supported query parameters:
;;   - lat (decimal latitude)
;;   - lon (decimal longitude)
;;   - alt (altitude in meters)
;;   - timestamp (epoch timestamp in seconds)
;;   - acc (accuracy in meters)
;;   - bat (battery level in percent)
;;   - sat (number of satellites)
;;   - useragent (device user agent)
;;   - speed (speed in meter per second)
;;   - bearing (bearing in decimal degrees)
;;
;; https://github.com/julien-nc/phonetrack/blob/main/doc/user.md
[ncpt]
id=0
name="NextCloud PhoneTrack"
method=GET
urlTemplate=https://server.example.org/{nextcloud}
urlPath=/apps/phonetrack/logGet
hasSession=true
hasDevice=true

;; https://github.com/julien-nc/phonetrack/blob/main/doc/user.md
[ncptpost]
id=1
name="NextCloud PhoneTrack (POST)"
method=POST
urlTemplate=https://server.example.org/{nextcloud}
urlPath=/apps/phonetrack/logPost
hasSession=true
hasDevice=true

;; https://sailfishos-chum.github.io/apps/harbour-find-my-device/
[findmydevice]
id=2
name="Sailfish FindMyDevice"
method=GET
urlTemplate=https://server.example.org/
urlPath=
hasSession=true
hasDevice=false
;;
;; Similar to PhoneTrack, but with the id/session in the query instead of the path
[traccar]
id=3
name="OsmAnd/Traccar"
method=GET
urlTemplate=https://server.example.org/
urlPath=
hasSession=true
hasDevice=false

;; https://github.com/nickfox/GpsTracker
[gpstracker]
id=4
name=GpsTracker
method=GET
urlTemplate=https://server.example.org/
urlPath=
hasSession=true
hasDevice=false

;; MUST have ID=99
;; the following placeholders will be replaced:
;;   - {latitude}
;;   - {longitude}
;;   - {session}
;;   - {useragent}
[custom]
id=99
name="Custom (GET)"
method=GET
urlTemplate=https://server.example.org/cgi-bin/submit?lat={latitude}&lon={longitude}&id={session}&useragent={useragent}
urlPath=
hasSession=false
hasDevice=false

